/**
 * Journey Map React Component
 *
 * Wraps the pure SVG generator from journey-map-svg.ts as a React component.
 * Marked 'use client' — safe to import in both client and server component trees.
 */

'use client';

export { generateJourneyMapSvg } from './journey-map-svg';
export type { JourneyStage } from './journey-map-svg';
import { generateJourneyMapSvg } from './journey-map-svg';

/**
 * JourneyMap React component — renders the SVG inline.
 */
export function JourneyMap({
  currentStage,
  locale = 'ar',
  animated = true,
  className,
}: {
  currentStage: string;
  locale?: 'ar' | 'en';
  animated?: boolean;
  className?: string;
}) {
  const svgString = generateJourneyMapSvg(currentStage, locale, animated);

  return (
    <div
      className={className}
      // SVG content is fully generated by us — no user input reaches here
      dangerouslySetInnerHTML={{ __html: svgString }}
      suppressHydrationWarning
    />
  );
}
